ENT.Base = "base_anim"
ENT.Type = "anim"
ENT.Category 			= "Other"
ENT.PrintName			= "Jukebox"
ENT.Author			= "Bishop"
ENT.Contact			= ""
ENT.Purpose			= "Good Diners need Good Jukeboxes"
ENT.Instructions		= "Turn it on, retard"
ENT.Spawnable			= true
ENT.AdminSpawnable		= true